export const US_STATES = [
  { name: 'Alabama', abbreviation: 'AL', translation: '阿拉巴马州' },
  { name: 'Alaska', abbreviation: 'AK', translation: '阿拉斯加州' },
  { name: 'American Samoa', abbreviation: 'AS', translation: '美属萨摩亚' },
  { name: 'Arizona', abbreviation: 'AZ', translation: '亚利桑那州' },
  { name: 'Arkansas', abbreviation: 'AR', translation: '阿肯色州' },
  { name: 'California', abbreviation: 'CA', translation: '加利福尼亚州' },
  { name: 'Colorado', abbreviation: 'CO', translation: '科罗拉多州' },
  { name: 'Connecticut', abbreviation: 'CT', translation: '康涅狄格州' },
  { name: 'Delaware', abbreviation: 'DE', translation: '特拉华州' },
  {
    name: 'District Of Columbia',
    abbreviation: 'DC',
    translation: '哥伦比亚特区',
  },
  {
    name: 'Federated States Of Micronesia',
    abbreviation: 'FM',
    translation: '密克罗尼西亚联邦',
  },
  { name: 'Florida', abbreviation: 'FL', translation: '佛罗里达州' },
  { name: 'Georgia', abbreviation: 'GA', translation: '乔治亚州' },
  { name: 'Guam Gu', abbreviation: 'GU', translation: '关岛' },
  { name: 'Hawaii', abbreviation: 'HI', translation: '夏威夷州' },
  { name: 'Idaho', abbreviation: 'ID', translation: '爱达荷州' },
  { name: 'Illinois', abbreviation: 'IL', translation: '伊利诺伊州' },
  { name: 'Indiana', abbreviation: 'IN', translation: '印第安纳州' },
  { name: 'Iowa', abbreviation: 'IA', translation: '爱荷华州' },
  { name: 'Kansas', abbreviation: 'KS', translation: '堪萨斯州' },
  { name: 'Kentucky', abbreviation: 'KY', translation: '肯塔基州' },
  { name: 'Louisiana', abbreviation: 'LA', translation: '路易斯安那州' },
  { name: 'Maine', abbreviation: 'ME', translation: '缅因州' },
  { name: 'Marshall Islands', abbreviation: 'MH', translation: '马绍尔群岛' },
  { name: 'Maryland', abbreviation: 'MD', translation: '马里兰州' },
  { name: 'Massachusetts', abbreviation: 'MA', translation: '马萨诸塞州' },
  { name: 'Michigan', abbreviation: 'MI', translation: '密歇根州' },
  { name: 'Minnesota', abbreviation: 'MN', translation: '明尼苏达州' },
  { name: 'Mississippi', abbreviation: 'MS', translation: '密西西比州' },
  { name: 'Missouri', abbreviation: 'MO', translation: '密苏里州' },
  { name: 'Montana', abbreviation: 'MT', translation: '蒙大拿州' },
  { name: 'Nebraska', abbreviation: 'NE', translation: '内布拉斯加州' },
  { name: 'Nevada', abbreviation: 'NV', translation: '内华达州' },
  { name: 'New Hampshire', abbreviation: 'NH', translation: '新罕布什尔州' },
  { name: 'New Jersey', abbreviation: 'NJ', translation: '新泽西州' },
  { name: 'New Mexico', abbreviation: 'NM', translation: '新墨西哥州' },
  { name: 'New York', abbreviation: 'NY', translation: '纽约州' },
  { name: 'North Carolina', abbreviation: 'NC', translation: '北卡罗来纳州' },
  { name: 'North Dakota', abbreviation: 'ND', translation: '北达科他州' },
  {
    name: 'Northern Mariana Islands',
    abbreviation: 'MP',
    translation: '北马里亚纳群岛',
  },
  { name: 'Ohio', abbreviation: 'OH', translation: '俄亥俄州' },
  { name: 'Oklahoma', abbreviation: 'OK', translation: '俄克拉何马州' },
  { name: 'Oregon', abbreviation: 'OR', translation: '俄勒冈州' },
  { name: 'Palau', abbreviation: 'PW', translation: '帕劳' },
  { name: 'Pennsylvania', abbreviation: 'PA', translation: '宾夕法尼亚州' },
  { name: 'Puerto Rico', abbreviation: 'PR', translation: '波多黎各' },
  { name: 'Rhode Island', abbreviation: 'RI', translation: '罗德岛' },
  { name: 'South Carolina', abbreviation: 'SC', translation: '南卡罗来纳州' },
  { name: 'South Dakota', abbreviation: 'SD', translation: '南达科他州' },
  { name: 'Tennessee', abbreviation: 'TN', translation: '田纳西州的' },
  { name: 'Texas', abbreviation: 'TX', translation: '得克萨斯州' },
  { name: 'Utah', abbreviation: 'UT', translation: '犹他州' },
  { name: 'Vermont', abbreviation: 'VT', translation: '佛蒙特州' },
  { name: 'Virgin Islands', abbreviation: 'VI', translation: '维尔京群岛' },
  { name: 'Virginia', abbreviation: 'VA', translation: '弗吉尼亚州' },
  { name: 'Washington', abbreviation: 'WA', translation: '华盛顿州' },
  { name: 'West Virginia', abbreviation: 'WV', translation: '西弗吉尼亚州' },
  { name: 'Wisconsin', abbreviation: 'WI', translation: '威斯康星州' },
  { name: 'Wyoming', abbreviation: 'WY', translation: '怀俄明州' },
];
